  - name: 鹊巢鸠居
    server: ws://120.77.213.218:25631
    token: >-
      000f0ea15ad84f58bfc19d00b07fcfd2
      0KNnSwBoxiPWQ3EHGr5PiThL2Dfny+adbohCqrbiIfF6t7kug/kTu7l7KpIxlmdWZQHpmPB5YtGCMeOt9dVOaQ==
      a6np685ccc2
    canlogin: true
    redboss: null
    leitai: false
    dungeons:
      first: false
      second: false
      third: cr yz/lw/shangu 0
      fourth: true
    war:
      family: false
      gang: true
      leader: false
    week:
      xiangyang: true
      yunbiao: false
      tazhu: null
      yaoshen: null
  - name: 达观知命
    server: ws://120.77.213.218:25631
    token: >-
      000f0ea15ad84f58bfc19d00b07fcfd2
      0KNnSwBoxiPWQ3EHGr5PiThL2Dfny+adbohCqrbiIfF6t7kug/kTu7l7KpIxlmdWZQHpmPB5YtGCMeOt9dVOaQ==
      c96s685cfad
    canlogin: true
    redboss: null
    leitai: false
    dungeons:
      first: false
      second: false
      third: cr yz/lw/shangu 0
      fourth: true
    war:
      family: false
      gang: true
      leader: false
    week:
      xiangyang: true
      yunbiao: false
      tazhu: null
      yaoshen: null
  - name: 山吟泽唱
    server: ws://120.77.213.218:25631
    token: >-
      000f0ea15ad84f58bfc19d00b07fcfd2
      0KNnSwBoxiPWQ3EHGr5PiThL2Dfny+adbohCqrbiIfF6t7kug/kTu7l7KpIxlmdWZQHpmPB5YtGCMeOt9dVOaQ==
      d0oq685cd1d
    canlogin: true
    redboss: null
    leitai: false
    dungeons:
      first: false
      second: false
      third: cr yz/lw/shangu 0
      fourth: true
    war:
      family: false
      gang: true
      leader: false
    week:
      xiangyang: true
      yunbiao: false
      tazhu: null
      yaoshen: null
  - name: 大庭广众
    server: ws://120.77.213.218:25631
    token: >-
      000f0ea15ad84f58bfc19d00b07fcfd2
      0KNnSwBoxiPWQ3EHGr5PiThL2Dfny+adbohCqrbiIfF6t7kug/kTu7l7KpIxlmdWZQHpmPB5YtGCMeOt9dVOaQ==
      ga3x685cf53
    canlogin: true
    redboss: null
    leitai: false
    dungeons:
      first: false
      second: false
      third: cr yz/lw/shangu 0
      fourth: true
    war:
      family: false
      gang: true
      leader: false
    week:
      xiangyang: true
      yunbiao: false
      tazhu: null
      yaoshen: null
  - name: 寸阴是惜
    server: ws://120.77.213.218:25631
    token: >-
      000f0ea15ad84f58bfc19d00b07fcfd2
      0KNnSwBoxiPWQ3EHGr5PiThL2Dfny+adbohCqrbiIfF6t7kug/kTu7l7KpIxlmdWZQHpmPB5YtGCMeOt9dVOaQ==
      gl9x685cddc
    canlogin: true
    redboss: null
    leitai: false
    dungeons:
      first: false
      second: false
      third: cr yz/lw/shangu 0
      fourth: true
    war:
      family: false
      gang: true
      leader: false
    week:
      xiangyang: true
      yunbiao: false
      tazhu: null
      yaoshen: null
  - name: 翩若惊鸿
    server: ws://120.77.213.218:25631
    token: >-
      000f0ea15ad84f58bfc19d00b07fcfd2
      0KNnSwBoxiPWQ3EHGr5PiThL2Dfny+adbohCqrbiIfF6t7kug/kTu7l7KpIxlmdWZQHpmPB5YtGCMeOt9dVOaQ==
      ienc685ce72
    canlogin: true
    redboss: null
    leitai: false
    dungeons:
      first: false
      second: false
      third: cr yz/lw/shangu 0
      fourth: true
    war:
      family: false
      gang: true
      leader: false
    week:
      xiangyang: true
      yunbiao: false
      tazhu: null
      yaoshen: null
  - name: 杀人如蒿
    server: ws://120.77.213.218:25631
    token: >-
      000f0ea15ad84f58bfc19d00b07fcfd2
      0KNnSwBoxiPWQ3EHGr5PiThL2Dfny+adbohCqrbiIfF6t7kug/kTu7l7KpIxlmdWZQHpmPB5YtGCMeOt9dVOaQ==
      nm0w685ce3b
    canlogin: true
    redboss: null
    leitai: false
    dungeons:
      first: false
      second: false
      third: cr yz/lw/shangu 0
      fourth: true
    war:
      family: false
      gang: true
      leader: false
    week:
      xiangyang: true
      yunbiao: false
      tazhu: null
      yaoshen: null
  - name: 遵养待时
    server: ws://120.77.213.218:25631
    token: >-
      000f0ea15ad84f58bfc19d00b07fcfd2
      0KNnSwBoxiPWQ3EHGr5PiThL2Dfny+adbohCqrbiIfF6t7kug/kTu7l7KpIxlmdWZQHpmPB5YtGCMeOt9dVOaQ==
      oqsh685cef4
    canlogin: true
    redboss: null
    leitai: false
    dungeons:
      first: false
      second: false
      third: cr yz/lw/shangu 0
      fourth: true
    war:
      family: false
      gang: true
      leader: false
    week:
      xiangyang: true
      yunbiao: false
      tazhu: null
      yaoshen: null
  - name: 洞鉴古今
    server: ws://120.77.213.218:25631
    token: >-
      000f0ea15ad84f58bfc19d00b07fcfd2
      0KNnSwBoxiPWQ3EHGr5PiThL2Dfny+adbohCqrbiIfF6t7kug/kTu7l7KpIxlmdWZQHpmPB5YtGCMeOt9dVOaQ==
      w786685cd81
    canlogin: true
    redboss: null
    leitai: false
    dungeons:
      first: false
      second: false
      third: cr yz/lw/shangu 0
      fourth: true
    war:
      family: false
      gang: true
      leader: false
    week:
      xiangyang: true
      yunbiao: false
      tazhu: null
      yaoshen: null