name: demo
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    continue-on-error: true
    steps:
      - name: 安装&&运行
        run: git clone https://github.com/KillES250/my-daily && tree my-daily
