name: wsmud
on: 
  workflow_dispatch:
//  schedule:
//    - cron: '5 1,8 * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    continue-on-error: true
    steps:
      - name: 安装&&运行
        run: git clone https://github.com/KillES250/my-daily && cd my-daily/wsmud && npm i && npm run rundaily
